# Site settings
title: duub.org
author: duub qnnp
email: saluton@duub.org
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://duub.org" # the base hostname & protocol for your site

# Outputting
permalink:     pretty
paginate: 1
paginate_path: "/page:num"

exclude: ["_plugins/category.rb"]

timezone: "Europe/Madrid"

twitter_username: "duubqnnp"
github_username:  "duub"

# Build settings
markdown: kramdown
#detach: true

# Front Matter defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "my-site"
  - scope:
      path: ""
    values:
      author: "duub qnnp"

collections:
    - cheatsheet
