# Site settings
title: duub.org
author: duub qnnp
email: saluton@duub.org
description: > # this means to ignore newlines until "baseurl:"
      Lloc web on aprendre i compartir l'aprés.
      Web creat amb l'ajuda de <a href=http://jekyllrb.com/>jekyll</a>
      i hostatjat a <a href=https://github.com/duub/duub.github.io>github</a>.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://duub.org" # the base hostname & protocol for your site
destination: ~/Development/duub.org-gandi/htdocs

# Outputting
permalink:     pretty
paginate: 5
paginate_path: "/page:num"

future: false

exclude: ["_plugins/category.rb"]

timezone: "Europe/Madrid"

twitter_username: "duubqnnp"
github_username:  "duub"

# Build settings
markdown: kramdown
#detach: true

# Front Matter defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "my-site"
  - scope:
      path: ""
    values:
      author: "duub qnnp"
